export type SpecialtyServicePage = {
  specialtySlug: string;
  serviceSlug: string;
  headline: string;
  subheadline: string;
  intro: string;
  considerations: { title: string; body: string }[];
  included: string[];
  stats: { value: string; label: string }[];
  metaTitle: string;
  metaDescription: string;
  keyword: string;
};

export const specialtyServicePages: SpecialtyServicePage[] = [
  // ── BEHAVIORAL HEALTH ──────────────────────────────────────────────
  {
    specialtySlug: "behavioral-health",
    serviceSlug: "call-center",
    headline: "Call Center Support for Behavioral Health Practices",
    subheadline: "Phone support built for the discretion and crisis-awareness behavioral health calls require — not a generic call center script.",
    intro: "Behavioral health call handling isn't just appointment scheduling — it requires discretion around sensitive information, sensitivity to callers who may be in crisis, and careful handling of authorization and session-limit questions that a generic call script doesn't anticipate. We staff phone support trained specifically for behavioral health and substance use calls, so patients get a consistent, appropriately careful experience whether they're scheduling a routine session or calling during a harder moment.",
    considerations: [
      { title: "Crisis-aware call handling", body: "Calls to a behavioral health practice sometimes come from someone in genuine distress. Staff need scripts and escalation paths that recognize this, not a standard scheduling script." },
      { title: "Confidentiality expectations are higher", body: "Behavioral health information carries extra sensitivity, and substance use contexts carry additional federal confidentiality considerations. Call handling needs to reflect that from the first hello." },
      { title: "Session-limit and authorization questions come up constantly", body: "Patients frequently ask whether they have sessions remaining or if a referral is still valid — call staff need visibility into authorization status to answer accurately, not just take a message." },
    ],
    included: [
      "Call handling protocols trained specifically for behavioral health and substance use calls",
      "Confidentiality practices aligned with heightened privacy expectations for substance use callers",
      "Authorization and session-limit status visibility for accurate patient answers",
      "Scheduling and rescheduling support across individual, group, and telehealth sessions",
      "Crisis-aware escalation paths coordinated with your clinical team",
      "Multilingual support for non-English-speaking patients",
    ],
    stats: [
      { value: "Crisis-Aware", label: "Call Handling Protocols" },
      { value: "Confidentiality-First", label: "Call Handling Standards" },
      { value: "Any Size", label: "Solo to Multi-Site Providers" },
    ],
    metaTitle: "Call Center Services for Behavioral Health Practices",
    metaDescription: "Discretion-first call handling for behavioral health and substance use practices — scheduling, authorization questions, and crisis-aware escalation.",
    keyword: "behavioral health call center services",
  },
  {
    specialtySlug: "behavioral-health",
    serviceSlug: "medical-billing-rcm",
    headline: "Full-Cycle RCM for Behavioral Health Practices",
    subheadline: "End-to-end revenue cycle management built around MBHO carve-outs, session limits, and parity-related denial patterns.",
    intro: "Handing over your entire revenue cycle for a behavioral health practice means more than standard coding and claims — it means a partner who already knows which MBHO to bill for which payer, tracks session authorization limits per patient without manual spreadsheets, and understands the parity-related denial patterns unique to mental health and substance use billing. We run your full cycle — eligibility, coding, submission, denial management, and reporting — with that specific expertise built in from day one.",
    considerations: [
      { title: "Carve-out routing has to be right before a claim is even coded", body: "Getting the payer entity wrong at the front end creates denials no amount of downstream RCM discipline can fix after the fact." },
      { title: "Session-limit tracking is a full-cycle responsibility, not a one-time check", body: "Limits reset, renew, and vary by payer — reporting has to track this on an ongoing basis, not just at intake." },
      { title: "Denial management needs parity-law context", body: "Some behavioral health denials are worth challenging on parity grounds, not just standard appeal templates." },
    ],
    included: [
      "Eligibility verification with correct MBHO/carve-out identification upfront",
      "Behavioral health-specific coding review — session-based CPT codes, add-on codes, telehealth modifiers",
      "Claim submission and clearinghouse management across MBHOs and medical carriers",
      "Session-limit and authorization tracking integrated into claims workflow",
      "Denial management with parity-law awareness for MH/SUD-specific denials",
      "Reporting broken out by payer and carve-out entity, not lumped into one view",
    ],
    stats: [
      { value: "MBHO-Aware", label: "Claims Routing" },
      { value: "Full-Cycle", label: "Eligibility to Reporting" },
      { value: "94%", label: "Target Clean Claim Rate" },
    ],
    metaTitle: "Medical Billing & RCM for Behavioral Health Practices",
    metaDescription: "Full-cycle revenue cycle management for behavioral health practices, built around MBHO carve-outs, session limits, and parity-related denial patterns.",
    keyword: "behavioral health revenue cycle management",
  },
  {
    specialtySlug: "behavioral-health",
    serviceSlug: "credentialing-enrollment",
    headline: "Credentialing for Behavioral Health Providers",
    subheadline: "Enrollment across the specific MBHOs and payers behavioral health providers actually bill — Optum, Magellan, Beacon, and more.",
    intro: "Credentialing a behavioral health provider means enrollment with the actual entities that manage mental health and substance use benefits — Optum Behavioral Health, Magellan, Beacon Health Options (Carelon), and others — which is a different panel than a medical carrier's general credentialing process. We manage that enrollment specifically, alongside standard CAQH, PECOS, and state Medicaid credentialing, so a new behavioral health provider isn't billable with the medical carrier but stuck waiting on the actual carve-out entity.",
    considerations: [
      { title: "MBHO enrollment is a separate process from medical-carrier credentialing", body: "Even once CAQH and the medical payer are squared away, the behavioral-health-specific carve-out entity often has its own separate application and timeline." },
      { title: "Telehealth licensure requirements vary by state", body: "Behavioral health providers seeing patients across state lines need licensure and enrollment coordinated per state, not assumed to transfer automatically." },
      { title: "Group practice enrollment for therapists and counselors has its own rules", body: "Enrolling licensed clinicians under a group NPI involves payer-specific requirements many credentialing processes overlook." },
    ],
    included: [
      "Enrollment with major MBHOs — Optum Behavioral Health, Magellan, Beacon/Carelon, and others",
      "Standard CAQH ProView, PECOS, and state Medicaid enrollment alongside MBHO-specific applications",
      "Multi-state telehealth licensure and enrollment coordination",
      "Group NPI enrollment support for licensed clinicians and counselors",
      "Real-time status tracking — billable, in-process, and expiring, broken out by payer type",
      "Re-credentialing managed proactively across both medical and behavioral health panels",
    ],
    stats: [
      { value: "MBHO-Specific", label: "Enrollment Expertise" },
      { value: "Multi-State", label: "Telehealth Licensure Support" },
      { value: "100%", label: "Deadline Tracking" },
    ],
    metaTitle: "Credentialing Services for Behavioral Health Providers",
    metaDescription: "MBHO, CAQH, PECOS, and state Medicaid credentialing for behavioral health providers, with multi-state telehealth licensure support.",
    keyword: "behavioral health credentialing services",
  },
  {
    specialtySlug: "behavioral-health",
    serviceSlug: "bpo-back-office",
    headline: "Back-Office Support for Behavioral Health Practices",
    subheadline: "Claims processing, denial management, and administrative support built around the volume and sensitivity of behavioral health operations.",
    intro: "Behavioral health practices generate a distinct kind of back-office load — high-frequency session-based claims, sensitive documentation that needs careful handling, and denial patterns tied to carve-outs and parity issues rather than typical coding errors. We provide claims processing, denial management, and administrative support calibrated to that specific load, so it doesn't fall to clinical staff or an overstretched office manager.",
    considerations: [
      { title: "Session-based claim volume adds up fast", body: "Weekly or twice-weekly sessions per patient generate a claims volume that outpaces what many practices' back-office capacity was built for." },
      { title: "Denial management here requires carve-out and parity knowledge", body: "A generalist back-office team without behavioral-health-specific denial expertise will miss patterns that a specialized team catches immediately." },
      { title: "Documentation handling needs extra care", body: "Behavioral health records carry additional confidentiality considerations that general administrative processes don't always account for." },
    ],
    included: [
      "Claims processing calibrated to session-based, high-frequency billing volume",
      "Denial management with MBHO carve-out and parity-law expertise",
      "Administrative support for authorization renewals and documentation requests",
      "Data entry and records handling aligned with behavioral health confidentiality practices",
      "Flexible capacity that scales with caseload, not fixed headcount",
      "Monthly reporting on throughput and denial resolution specific to behavioral health claims",
    ],
    stats: [
      { value: "Session-Based", label: "Claims Volume Handling" },
      { value: "Carve-Out Aware", label: "Denial Management" },
      { value: "100%", label: "HIPAA-Compliant Operations" },
    ],
    metaTitle: "Back-Office Outsourcing for Behavioral Health Practices",
    metaDescription: "Claims processing, denial management, and administrative support built around behavioral health's session-based billing and confidentiality needs.",
    keyword: "behavioral health back office outsourcing",
  },

  // ── PRIMARY CARE ───────────────────────────────────────────────────
  {
    specialtySlug: "primary-care",
    serviceSlug: "call-center",
    headline: "Call Center Support for Primary Care Practices",
    subheadline: "High-volume scheduling, CCM/AWV outreach, and triage support sized to your patient panel.",
    intro: "Primary care generates the highest call volume of any specialty — routine scheduling, prescription refill requests, CCM and AWV outreach calls, and basic triage questions, all day, every day. We staff call support sized to that volume specifically, including the proactive outreach that captures CCM and AWV revenue most practices don't have staff time to make happen consistently.",
    considerations: [
      { title: "Volume is the defining challenge, not complexity", body: "Primary care doesn't need specialized call handling as much as it needs enough capacity to keep up with sheer call volume without hold times climbing." },
      { title: "CCM/AWV outreach calls are revenue-generating, not just administrative", body: "Proactively calling patients due for an Annual Wellness Visit or enrolled in Chronic Care Management captures billable revenue that goes uncaptured without dedicated outbound calling." },
      { title: "Basic triage questions need a clear escalation path", body: "Front-line call staff need clear guidance on what can be handled by phone versus what needs a nurse or provider, without creating delay either way." },
    ],
    included: [
      "High-volume scheduling and rescheduling support",
      "Proactive CCM and AWV outreach calling to capture billable revenue",
      "Prescription refill request handling and routing",
      "Basic triage question handling with clear clinical escalation paths",
      "Standardized scripting and QA across your full call volume",
      "24/7 or extended-hours coverage for after-hours call overflow",
    ],
    stats: [
      { value: "High-Volume", label: "Scheduling Capacity" },
      { value: "CCM/AWV", label: "Outreach Calling Included" },
      { value: "24/7", label: "Coverage Available" },
    ],
    metaTitle: "Call Center Services for Primary Care Practices",
    metaDescription: "High-volume scheduling, CCM/AWV outreach calling, and triage support for primary care practices of any size.",
    keyword: "primary care call center services",
  },
  {
    specialtySlug: "primary-care",
    serviceSlug: "medical-billing-rcm",
    headline: "Full-Cycle RCM for Primary Care Practices",
    subheadline: "Revenue cycle management built around E/M coding accuracy and CCM/AWV capture at high claim volume.",
    intro: "Primary care sees the highest claim volume of any specialty, which means small per-claim inefficiencies compound fast. We run full-cycle RCM built around what actually moves the needle for primary care specifically — provider-level E/M coding accuracy, systematic CCM/AWV billing capture, and denial tracking at the volume primary care practices actually generate.",
    considerations: [
      { title: "E/M coding variance is the single biggest lever at this volume", body: "A small, consistent undercoding pattern across thousands of annual visits adds up to real revenue lost, more than almost any other single fix." },
      { title: "CCM and AWV billing requires systematic patient tracking", body: "Capturing this revenue reliably takes a dedicated identification and tracking process, not an occasional reminder to front-desk staff." },
      { title: "Denial patterns at high volume need automated flagging", body: "Manually reviewing denials one by one doesn't scale at primary care's claim volume — patterns need to be caught systematically." },
    ],
    included: [
      "Provider-level E/M coding audits and standardization",
      "AWV billing (G0438/G0439) with separate E/M capture where appropriate",
      "Chronic Care Management (CCM) program billing infrastructure and patient tracking",
      "High-volume claim scrubbing and electronic submission",
      "Denial rate tracking by provider and CPT code at volume",
      "Clean claim rate and AR days reporting calibrated to primary care claim volume",
    ],
    stats: [
      { value: "Provider-Level", label: "E/M Coding Accuracy" },
      { value: "CCM/AWV", label: "Revenue Capture Built In" },
      { value: "94%", label: "Target Clean Claim Rate" },
    ],
    metaTitle: "Medical Billing & RCM for Primary Care Practices",
    metaDescription: "Full-cycle revenue cycle management for primary care, built around E/M coding accuracy and CCM/AWV revenue capture at high claim volume.",
    keyword: "primary care revenue cycle management",
  },
  {
    specialtySlug: "primary-care",
    serviceSlug: "credentialing-enrollment",
    headline: "Credentialing for Primary Care Providers",
    subheadline: "Enrollment across every commercial payer, Medicare, and Medicaid — sized for a solo provider or a growing panel.",
    intro: "Primary care credentialing is often the first payer-enrollment experience a new practice or provider goes through, and getting CAQH, PECOS, and state Medicaid right the first time avoids a billing delay that can stretch well past a provider's actual start date. We manage that enrollment specifically for primary care providers, from a first-time solo practice to a group adding its next provider.",
    considerations: [
      { title: "A new provider's start date and their billable date are two different things", body: "Credentialing timelines don't move because a provider is ready to see patients — that gap needs to be planned for, not discovered." },
      { title: "Panel status with major commercial payers varies practice to practice", body: "Some payer panels are open, others require justification or are effectively closed in certain markets — knowing this ahead of time avoids wasted applications." },
      { title: "Re-credentialing cycles are easy to lose track of at a growing practice", body: "As a primary care practice adds providers, tracking every provider's re-credentialing deadline manually gets unreliable fast." },
    ],
    included: [
      "CAQH ProView setup and ongoing quarterly attestation management",
      "Medicare PECOS enrollment and state Medicaid enrollment",
      "Commercial payer panel applications, including closed-panel justification support",
      "New-provider enrollment timed against your actual start date, not just submission date",
      "Real-time status dashboard across all payers",
      "Re-credentialing managed proactively as your provider panel grows",
    ],
    stats: [
      { value: "1 to 40+", label: "Providers Credentialed Concurrently" },
      { value: "60–120d", label: "Typical Enrollment Window" },
      { value: "100%", label: "Deadline Tracking" },
    ],
    metaTitle: "Credentialing Services for Primary Care Providers",
    metaDescription: "CAQH, PECOS, state Medicaid, and commercial payer credentialing for primary care providers and practices of any size.",
    keyword: "primary care credentialing services",
  },
  {
    specialtySlug: "primary-care",
    serviceSlug: "bpo-back-office",
    headline: "Back-Office Support for Primary Care Practices",
    subheadline: "Claims processing and administrative support sized to primary care's high patient volume.",
    intro: "Primary care's back-office load scales directly with patient volume — data entry, document processing, and claims intake grow every time your panel grows, regardless of whether staffing keeps pace. We provide back-office support calibrated specifically to that volume, absorbing the administrative load that would otherwise compete with patient care for your staff's time.",
    considerations: [
      { title: "Administrative load scales with panel size, not with staffing", body: "A growing patient panel means growing paperwork, referrals, and records requests, whether or not you've hired to match it." },
      { title: "Claims processing backlogs are the first visible symptom of a strained back office", body: "At high volume, a small dip in processing speed compounds into a real backlog fast." },
      { title: "Denial management needs dedicated attention, not leftover time", body: "At primary care's claim volume, working denials properly takes focused time that's hard to find between patient-facing duties." },
    ],
    included: [
      "Claims processing calibrated to high-volume primary care intake",
      "Denial management and appeals handled by a dedicated team",
      "Administrative support for referrals, records requests, and documentation",
      "Data entry support that scales with patient panel growth",
      "Integration with major primary care EHR and practice management systems",
      "Monthly reporting on throughput and denial resolution",
    ],
    stats: [
      { value: "High-Volume", label: "Claims Processing" },
      { value: "30–40%", label: "Typical Cost Reduction" },
      { value: "Flex", label: "Capacity Scales With Panel Growth" },
    ],
    metaTitle: "Back-Office Outsourcing for Primary Care Practices",
    metaDescription: "Claims processing, denial management, and administrative support sized to primary care's high patient volume.",
    keyword: "primary care back office outsourcing",
  },

  // ── CARDIOLOGY ─────────────────────────────────────────────────────
  {
    specialtySlug: "cardiology",
    serviceSlug: "call-center",
    headline: "Call Center Support for Cardiology Practices",
    subheadline: "Pre-procedure coordination, stress-test scheduling, and prior auth status calls handled by staff who know the difference between them.",
    intro: "Cardiology calls aren't just scheduling — patients calling about a stress test need different prep instructions than someone confirming a device follow-up, and prior authorization status calls to payers require someone who understands what's actually being authorized. We staff call support trained specifically on cardiology's mix of routine scheduling and procedure-specific coordination.",
    considerations: [
      { title: "Pre-procedure instructions vary by test type", body: "A patient calling about a stress test needs different guidance than one calling about an echo or a device check — generic scripts miss this." },
      { title: "Prior auth status calls require real understanding of what's being authorized", body: "Imaging, interventional procedures, and device implants all have different authorization pathways; call staff need to know which is which to give an accurate answer." },
      { title: "Same-day cancellations on procedure slots are costly", body: "Missed or unclear pre-procedure calls contribute to cancellations on high-value procedure slots that are expensive to leave empty." },
    ],
    included: [
      "Scheduling and pre-procedure instruction calls tailored by test/procedure type",
      "Prior authorization status calls to payers and delegated review vendors",
      "Device follow-up and monitoring appointment coordination",
      "Denial escalation calls specific to cardiology imaging and procedures",
      "Standardized scripting across stress test, echo, cath lab, and device scheduling",
      "24/7 or extended-hours coverage for after-hours patient calls",
    ],
    stats: [
      { value: "Procedure-Specific", label: "Call Scripting" },
      { value: "Auth-Aware", label: "Prior Auth Status Calls" },
      { value: "24/7", label: "Coverage Available" },
    ],
    metaTitle: "Call Center Services for Cardiology Practices",
    metaDescription: "Pre-procedure coordination, stress-test scheduling, and prior authorization status calls handled by staff trained specifically for cardiology.",
    keyword: "cardiology call center services",
  },
  {
    specialtySlug: "cardiology",
    serviceSlug: "medical-billing-rcm",
    headline: "Full-Cycle RCM for Cardiology Practices",
    subheadline: "Revenue cycle management built around prior authorization volume, modifier 26 compliance, and device billing.",
    intro: "Handing over your full cardiology revenue cycle means working with a partner who already understands modifier 26 versus global billing, device and implant cost-recovery documentation, and the prior authorization volume that comes with imaging and interventional procedures. We run eligibility, coding, submission, denial management, and reporting with that expertise built in, not bolted on.",
    considerations: [
      { title: "Modifier 26 errors are a systematic risk, not an occasional mistake", body: "Reading studies at outside sites makes it easy to bill the wrong component consistently until someone audits for the pattern specifically." },
      { title: "Device billing carries real per-case financial risk", body: "A misbilled high-cost implant is a meaningful loss on that single claim — this needs documentation review built into the workflow, not caught after the fact." },
      { title: "Prior authorization volume needs dedicated tracking", body: "Imaging, interventional procedures, and device implants all require authorization, and the volume routinely outpaces ad hoc tracking." },
    ],
    included: [
      "Prior authorization tracking across imaging, interventional, and device procedures",
      "Modifier 26 / global-vs-professional compliance built into coding review",
      "Device and implant billing with cost-recovery documentation review",
      "Claim scrubbing and submission calibrated to cardiology-specific edits",
      "Denial management sorted by payer, procedure type, and root cause",
      "Clean claim rate and AR reporting broken out by procedure category",
    ],
    stats: [
      { value: "Modifier-Aware", label: "Coding Review" },
      { value: "Full-Cycle", label: "Eligibility to Reporting" },
      { value: "94%", label: "Target Clean Claim Rate" },
    ],
    metaTitle: "Medical Billing & RCM for Cardiology Practices",
    metaDescription: "Full-cycle revenue cycle management for cardiology practices, built around prior authorization, modifier 26 compliance, and device billing.",
    keyword: "cardiology revenue cycle management",
  },
  {
    specialtySlug: "cardiology",
    serviceSlug: "credentialing-enrollment",
    headline: "Credentialing for Cardiology Providers",
    subheadline: "Payer enrollment and hospital privileging support for cardiologists reading and operating across multiple sites.",
    intro: "Cardiology credentialing often involves more than standard payer enrollment — cardiologists reading studies at outside imaging centers or performing procedures at hospital facilities need privileging alongside CAQH, PECOS, and commercial payer enrollment. We manage both sides of that so a cardiologist isn't billable with a payer but still waiting on facility privileges, or vice versa.",
    considerations: [
      { title: "Hospital privileging and payer enrollment run on separate clocks", body: "A cardiologist can be enrolled with every payer and still not be able to perform procedures at a facility without separate privileging — and the reverse is just as common." },
      { title: "Reading privileges at outside imaging sites need their own credentialing trail", body: "Cardiologists reading studies at facilities they don't own often need distinct arrangements tracked separately from their primary practice credentialing." },
      { title: "Device and procedure-specific payer requirements add complexity", body: "Some payers have specific credentialing or certification requirements tied to interventional procedures or device implantation specifically." },
    ],
    included: [
      "CAQH ProView, PECOS, and state Medicaid enrollment for cardiology providers",
      "Hospital and facility privileging coordination alongside payer credentialing",
      "Reading-site credentialing for outside imaging arrangements",
      "Commercial payer enrollment including procedure-specific requirements",
      "Real-time status dashboard across payers and facilities",
      "Re-credentialing managed proactively across your full provider roster",
    ],
    stats: [
      { value: "Privileging-Aware", label: "Credentialing Coordination" },
      { value: "1 to 40+", label: "Providers Credentialed Concurrently" },
      { value: "100%", label: "Deadline Tracking" },
    ],
    metaTitle: "Credentialing Services for Cardiology Providers",
    metaDescription: "Payer enrollment and hospital privileging support for cardiology providers reading and operating across multiple sites.",
    keyword: "cardiology credentialing services",
  },
  {
    specialtySlug: "cardiology",
    serviceSlug: "bpo-back-office",
    headline: "Back-Office Support for Cardiology Practices",
    subheadline: "Claims processing and denial management built around cardiology's high-value, high-scrutiny procedure billing.",
    intro: "Cardiology's back-office load carries more per-claim financial risk than most specialties — a single denied device case or misprocessed prior authorization can outweigh a week of routine claims. We provide claims processing and denial management calibrated specifically to that risk profile, with the payer-specific appeal expertise cardiology billing actually requires.",
    considerations: [
      { title: "Per-claim financial risk is higher here than most specialties", body: "A single high-cost device or interventional procedure claim carries more weight than routine visit billing, so back-office accuracy matters proportionally more." },
      { title: "Denial appeals require cardiology-specific payer knowledge", body: "Generic appeal templates don't address the modifier and authorization-specific reasons cardiology claims actually get denied." },
      { title: "Documentation review needs to happen before submission, not after denial", body: "Catching a device documentation gap before submission is far cheaper than appealing after the fact." },
    ],
    included: [
      "Claims processing calibrated to high-value cardiology procedure billing",
      "Denial management with cardiology-specific payer and modifier expertise",
      "Pre-submission documentation review for device and implant claims",
      "Administrative support for prior authorization paperwork and follow-up",
      "Flexible capacity that scales with procedure volume",
      "Monthly reporting on throughput, denial resolution, and cost per claim",
    ],
    stats: [
      { value: "High-Value Claims", label: "Processing Accuracy" },
      { value: "Cardiology-Specific", label: "Denial Appeal Expertise" },
      { value: "100%", label: "HIPAA-Compliant Operations" },
    ],
    metaTitle: "Back-Office Outsourcing for Cardiology Practices",
    metaDescription: "Claims processing and denial management built around cardiology's high-value, high-scrutiny procedure billing.",
    keyword: "cardiology back office outsourcing",
  },

  // ── MULTI-SPECIALTY GROUPS ─────────────────────────────────────────
  {
    specialtySlug: "multi-specialty-groups",
    serviceSlug: "call-center",
    headline: "Call Center Support for Multi-Specialty Practices",
    subheadline: "One consistent phone experience across every department, from primary care to procedural specialties.",
    intro: "A multi-specialty practice needs call handling that's consistent across departments but flexible enough to handle each specialty's actual call patterns — a primary care scheduling call is nothing like a cardiology pre-procedure call. We staff phone support that maintains one standard of service across your whole practice while still routing and handling each department's calls correctly.",
    considerations: [
      { title: "Different departments generate genuinely different call types", body: "A single generic script doesn't hold up across primary care volume, behavioral health discretion needs, and cardiology procedure coordination at once." },
      { title: "Routing calls to the right department accurately matters more here", body: "Multi-specialty practices need calls directed correctly the first time, not transferred repeatedly across departments." },
      { title: "Consistency across departments is what patients actually notice", body: "When one department's phone experience is dramatically different from another's, it reads as disorganization rather than specialization." },
    ],
    included: [
      "Department-specific call scripts unified under one standard of service",
      "Accurate call routing across every specialty in your practice",
      "Scheduling, prior auth, and billing question handling calibrated per department",
      "Standardized QA scoring across all departments, not just some",
      "Centralized reporting on call volume and resolution by department",
      "24/7 or extended-hours coverage across your full practice",
    ],
    stats: [
      { value: "Multi-Department", label: "Consistent Call Standards" },
      { value: "Accurate Routing", label: "Across Every Specialty" },
      { value: "24/7", label: "Coverage Available" },
    ],
    metaTitle: "Call Center Services for Multi-Specialty Practices",
    metaDescription: "Consistent, department-aware call center support across every specialty in your multi-specialty practice.",
    keyword: "multi specialty call center services",
  },
  {
    specialtySlug: "multi-specialty-groups",
    serviceSlug: "medical-billing-rcm",
    headline: "Full-Cycle RCM for Multi-Specialty Practices",
    subheadline: "One revenue cycle operation with the coding depth to handle every specialty under your roof correctly.",
    intro: "Running RCM across multiple specialties means applying genuinely different coding logic — a cardiology claim, a behavioral health session, and a primary care visit all follow different rules — while still rolling up into one coherent operation your leadership can actually read. We run full-cycle RCM with specialty-specific coding depth inside a single, standardized operation.",
    considerations: [
      { title: "Specialty-specific coding depth can't be generalized away", body: "A biller excellent at primary care E/M coding may not have the depth for cardiology device billing or behavioral health carve-outs — both need real expertise, not a single generalist approach." },
      { title: "Cross-specialty reporting has to normalize genuinely different billing profiles", body: "Comparing a behavioral health department's numbers directly against a cardiology department's without accounting for different reimbursement and denial profiles hides more than it reveals." },
      { title: "Internal referral coordination is a distinct billing risk", body: "When a patient sees two specialists within your practice, avoiding duplicate E/M billing requires cross-departmental awareness most systems don't build in." },
    ],
    included: [
      "Specialty-specific coding expertise across every department in your practice",
      "Unified claim submission and clearinghouse management across all specialties",
      "Cross-specialty denial and AR reporting normalized by department",
      "Internal referral and duplicate-billing coordination across departments",
      "Department-level and practice-wide performance benchmarking",
      "One standardized RCM operation instead of siloed department-by-department billing",
    ],
    stats: [
      { value: "Multi-Specialty", label: "Coding Depth in One Operation" },
      { value: "Unified", label: "Cross-Department Reporting" },
      { value: "94%", label: "Target Clean Claim Rate" },
    ],
    metaTitle: "Medical Billing & RCM for Multi-Specialty Practices",
    metaDescription: "Full-cycle revenue cycle management with specialty-specific coding depth, unified across every department in your multi-specialty practice.",
    keyword: "multi specialty revenue cycle management",
  },
  {
    specialtySlug: "multi-specialty-groups",
    serviceSlug: "credentialing-enrollment",
    headline: "Credentialing for Multi-Specialty Practices",
    subheadline: "Enrollment managed across every specialty and payer relationship in your practice, from one dashboard.",
    intro: "Credentialing a multi-specialty practice means managing enrollment across different provider types, different payer relationships per specialty, and potentially different MBHO or facility-specific requirements depending on which department a provider belongs to. We manage all of it from one real-time dashboard, so leadership always knows exactly which providers are billable across every department.",
    considerations: [
      { title: "Different departments have different credentialing requirements", body: "A behavioral health clinician's MBHO enrollment and a cardiologist's facility privileging are entirely different processes running at the same time." },
      { title: "Cross-departmental visibility is easy to lose without a single system", body: "Tracking credentialing status separately per department creates blind spots exactly where leadership needs the clearest view." },
      { title: "New department launches multiply the credentialing workload at once", body: "Adding a new specialty to your practice means credentialing an entirely new category of provider against payer requirements you may not have dealt with before." },
    ],
    included: [
      "CAQH, PECOS, and state Medicaid enrollment across every specialty in your practice",
      "Department-specific credentialing (MBHO enrollment, facility privileging, etc.) managed in parallel",
      "Real-time status dashboard broken out by department and payer",
      "New-department launch credentialing sprints",
      "Delegated credentialing agreement support where applicable",
      "Re-credentialing managed proactively across your full multi-specialty roster",
    ],
    stats: [
      { value: "Cross-Department", label: "Credentialing Visibility" },
      { value: "1 to 40+", label: "Providers Credentialed Concurrently" },
      { value: "100%", label: "Deadline Tracking" },
    ],
    metaTitle: "Credentialing Services for Multi-Specialty Practices",
    metaDescription: "Credentialing and payer enrollment managed across every specialty and department in your multi-specialty practice, from one dashboard.",
    keyword: "multi specialty credentialing services",
  },
  {
    specialtySlug: "multi-specialty-groups",
    serviceSlug: "bpo-back-office",
    headline: "Back-Office Support for Multi-Specialty Practices",
    subheadline: "Claims processing and denial management with the depth to handle every department's distinct billing profile.",
    intro: "A multi-specialty practice's back-office load isn't uniform — a cardiology department's high-value device claims, a behavioral health department's session-based volume, and a primary care department's sheer claim count all need different handling. We provide back-office support with the depth to handle each department correctly, rolled up into one operation instead of siloed vendors per specialty.",
    considerations: [
      { title: "Each department's claims need different handling, not one generic process", body: "Treating every department's back-office needs identically misses the specific patterns each specialty actually generates." },
      { title: "Denial management needs specialty-specific expertise per department", body: "A denial pattern in cardiology billing looks nothing like one in behavioral health billing, and appeal expertise needs to reflect that." },
      { title: "One vendor across departments beats managing several", body: "Multi-specialty practices juggling separate back-office vendors per department lose the benefit of unified reporting and accountability." },
    ],
    included: [
      "Claims processing calibrated to each department's specific billing profile",
      "Denial management with specialty-specific expertise across departments",
      "Unified administrative support instead of siloed per-department vendors",
      "Cross-department reporting on throughput and denial resolution",
      "Flexible capacity that scales with whichever department needs it most",
      "One dedicated operations team overseeing your full multi-specialty back office",
    ],
    stats: [
      { value: "Cross-Specialty", label: "Denial Management Depth" },
      { value: "Unified", label: "One Vendor, Every Department" },
      { value: "100%", label: "HIPAA-Compliant Operations" },
    ],
    metaTitle: "Back-Office Outsourcing for Multi-Specialty Practices",
    metaDescription: "Claims processing and denial management with the depth to handle every department's distinct billing profile in your multi-specialty practice.",
    keyword: "multi specialty back office outsourcing",
  },

  // ── LABS & DIAGNOSTICS ─────────────────────────────────────────────
  {
    specialtySlug: "laboratory-diagnostics",
    serviceSlug: "call-center",
    headline: "Call Center Support for Labs & Diagnostic Centers",
    subheadline: "Results-related calls, ABN questions, and referring-provider coordination handled with lab-specific care.",
    intro: "Lab and diagnostic center calls carry their own considerations — patients asking about results, which need to be handled carefully and often routed to ordering providers rather than answered directly, questions about ABN forms and out-of-pocket costs, and coordination calls with referring providers and their offices. We staff call support trained on these lab-specific patterns.",
    considerations: [
      { title: "Results-related calls need careful routing, not direct answers", body: "Patients calling about results typically need to be directed back to their ordering provider, and call staff need clear protocols for this every time." },
      { title: "ABN and cost questions come up constantly", body: "Patients frequently call asking why they received an ABN or what a test will cost out of pocket — staff need visibility into this to answer accurately." },
      { title: "Referring-provider coordination is its own call category", body: "Labs field a steady stream of calls from referring practices about order status, requisitions, and result delivery — a different workflow than patient calls entirely." },
    ],
    included: [
      "Results-call handling with proper routing back to ordering providers",
      "ABN and out-of-pocket cost question support",
      "Referring-provider coordination calls — order status, requisitions, result delivery",
      "Scheduling support for specimen collection and diagnostic appointments",
      "Standardized scripting across patient and referring-provider call types",
      "Extended-hours coverage for labs running beyond standard office hours",
    ],
    stats: [
      { value: "Referral-Aware", label: "Provider Coordination Calls" },
      { value: "ABN-Ready", label: "Cost Question Support" },
      { value: "24/7", label: "Coverage Available" },
    ],
    metaTitle: "Call Center Services for Labs & Diagnostic Centers",
    metaDescription: "Results-related calls, ABN questions, and referring-provider coordination handled with lab-specific call center support.",
    keyword: "lab diagnostic call center services",
  },
  {
    specialtySlug: "laboratory-diagnostics",
    serviceSlug: "medical-billing-rcm",
    headline: "Full-Cycle RCM for Labs & Diagnostic Centers",
    subheadline: "Revenue cycle management built around PAMA reporting, LCD compliance, and ABN discipline — not standard physician billing.",
    intro: "Lab billing runs on PAMA fee schedules, Local Coverage Determinations, and ABN rules that don't have close equivalents in physician office billing. We run full-cycle RCM for labs and diagnostic centers with that regulatory framework built into every stage — eligibility, LCD-matched coding, submission, denial management, and reporting.",
    considerations: [
      { title: "LCD compliance has to happen before submission, not after denial", body: "Systematic diagnosis-to-test matching against Local Coverage Determinations needs to be part of the workflow, not a post-denial discovery." },
      { title: "PAMA reporting obligations are easy to underweight", body: "Getting private payer rate and volume reporting wrong has downstream consequences for reimbursement that show up months later, disconnected from the original filing." },
      { title: "ABN workflows need to trigger correctly, not become a blanket habit", body: "ABNs only protect revenue when issued before testing, tied to genuine non-coverage expectations — not as a routine hedge." },
    ],
    included: [
      "PAMA-compliant billing and reporting for routine and specialty lab panels",
      "Systematic LCD compliance checking against diagnosis codes before submission",
      "ABN issuance workflows tied to actual coverage determinations",
      "Molecular, genetic, and toxicology billing with audit-ready documentation",
      "Reflex and add-on test billing rule management",
      "Denial analysis by test type and payer",
    ],
    stats: [
      { value: "PAMA-Compliant", label: "Billing & Reporting" },
      { value: "LCD-Matched", label: "Coding Before Submission" },
      { value: "Audit-Ready", label: "Molecular & Toxicology Billing" },
    ],
    metaTitle: "Medical Billing & RCM for Labs & Diagnostic Centers",
    metaDescription: "Full-cycle revenue cycle management for labs, built around PAMA reporting, LCD compliance, and ABN discipline.",
    keyword: "lab diagnostic revenue cycle management",
  },
  {
    specialtySlug: "laboratory-diagnostics",
    serviceSlug: "credentialing-enrollment",
    headline: "Credentialing for Labs & Diagnostic Centers",
    subheadline: "CLIA-aware enrollment and payer credentialing for independent labs and diagnostic networks.",
    intro: "Credentialing a lab or diagnostic center involves considerations physician-office credentialing doesn't — CLIA certification status tied to payer enrollment, facility-level credentialing alongside any billing provider NPIs, and payer-specific requirements for high-volume or specialty testing categories. We manage enrollment with that framework built in from the start.",
    considerations: [
      { title: "CLIA certification and payer enrollment are connected but separate", body: "Payers verify CLIA status as part of enrollment, and a lapse or gap in either one can affect the other unexpectedly." },
      { title: "Facility-level and provider-level credentialing both matter for labs", body: "Labs often need both the facility and any supervising or ordering providers properly credentialed, which is a different structure than a typical physician practice." },
      { title: "Specialty testing categories sometimes carry their own payer requirements", body: "Molecular, genetic, and toxicology testing categories occasionally have additional payer-specific credentialing or certification expectations." },
    ],
    included: [
      "Facility and provider-level credentialing coordinated together",
      "CLIA certification status tracking alongside payer enrollment",
      "Commercial payer, Medicare, and Medicaid enrollment for labs and diagnostic centers",
      "Specialty testing category credentialing (molecular, genetic, toxicology) where required",
      "Real-time status dashboard across facility and provider enrollment",
      "Re-credentialing and CLIA renewal tracking managed proactively",
    ],
    stats: [
      { value: "CLIA-Aware", label: "Enrollment Coordination" },
      { value: "Facility + Provider", label: "Credentialing Managed Together" },
      { value: "100%", label: "Deadline Tracking" },
    ],
    metaTitle: "Credentialing Services for Labs & Diagnostic Centers",
    metaDescription: "CLIA-aware payer credentialing for independent labs and diagnostic centers, covering both facility and provider-level enrollment.",
    keyword: "lab diagnostic credentialing services",
  },
  {
    specialtySlug: "laboratory-diagnostics",
    serviceSlug: "bpo-back-office",
    headline: "Back-Office Support for Labs & Diagnostic Centers",
    subheadline: "Claims processing and denial management built around lab-specific compliance and audit exposure.",
    intro: "Labs carry a distinct back-office risk profile — molecular and toxicology billing draws sustained federal program-integrity scrutiny, LCD compliance has to be checked at real volume, and ABN documentation needs to hold up if questioned. We provide claims processing and denial management with that specific risk profile in mind, not a generic back-office approach borrowed from physician billing.",
    considerations: [
      { title: "Audit exposure is higher for certain test categories", body: "Molecular and toxicology billing draws disproportionate scrutiny as a category, regardless of any individual lab's actual practices, so documentation discipline matters more here." },
      { title: "LCD compliance checking has to scale with test volume", body: "Manual verification works at low volume and stops working well before real scale — back-office processes need to be systematic from early on." },
      { title: "Denial management needs to distinguish LCD, ABN, and coding-error causes", body: "Treating every lab denial the same way misses that the fix looks completely different depending on which of these caused it." },
    ],
    included: [
      "Claims processing calibrated to lab and diagnostic test volume",
      "Denial management sorted by LCD, ABN, and coding-error root cause",
      "Audit-ready documentation support for molecular and toxicology billing",
      "Administrative support for reflex and add-on test billing rules",
      "Flexible capacity that scales with test volume",
      "Monthly reporting on throughput, denial resolution, and audit-readiness",
    ],
    stats: [
      { value: "Audit-Ready", label: "Molecular & Toxicology Support" },
      { value: "LCD-Sorted", label: "Denial Root-Cause Analysis" },
      { value: "100%", label: "HIPAA-Compliant Operations" },
    ],
    metaTitle: "Back-Office Outsourcing for Labs & Diagnostic Centers",
    metaDescription: "Claims processing and denial management built around lab-specific compliance and audit exposure for labs and diagnostic centers.",
    keyword: "lab diagnostic back office outsourcing",
  },
];

export function getSpecialtyServicePage(specialtySlug: string, serviceSlug: string): SpecialtyServicePage | undefined {
  return specialtyServicePages.find((p) => p.specialtySlug === specialtySlug && p.serviceSlug === serviceSlug);
}

export function getCombosForSpecialty(specialtySlug: string): SpecialtyServicePage[] {
  return specialtyServicePages.filter((p) => p.specialtySlug === specialtySlug);
}

export function getCombosForService(serviceSlug: string): SpecialtyServicePage[] {
  return specialtyServicePages.filter((p) => p.serviceSlug === serviceSlug);
}
